config/routes.rb
Rails.application.routes.draw do
  resources :user_images
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "user_images/:id/stitchify", to: "user_images#stitchify", as: "stitchify"

  root  "user_images#index"
  match "*path", to: redirect("/"), via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user_image.rb
require "fileutils"

class UserImage < ApplicationRecord
  validates :name, presence: true
  validates :stitch_pic, presence: true
  validates :acknowledged_privacy, presence: true
  validate :privacy_acknowledged
  mount_uploader :stitch_pic, StitchPicUploader
  after_initialize :set_default_vars

  def privacy_acknowledged
    if acknowledged_privacy == 1 || acknowledged_privacy == true
      puts acknowledged_privacy
      puts "in the if block"
    else
      puts acknowledged_privacy
      puts "in the else block"
      errors.add(:acknowledged_privacy, 'must be checked')
    end
  end

  def set_default_vars
    self.grid_width  ||= 75           #will set the default value only if it's nil
    self.px_size ||= 10
    self.number_of_colors ||= 12
  end

  def stitchify
    FileUtils.touch(stitch_path) if stitched_file?
    stitchified = Stitchifier.new(stitch_pic.path, grid_width, px_size, number_of_colors, stitch_path)
  end

  def stitch_path
    sanitized_name = self.name.gsub(/[^0-9A-z.\-]/, '_')
    stitchpath = "#{Rails.root}/public/uploads/stitched/#{id}_#{sanitized_name}_stitched.svg"
  end

  def stitched_file?
    File.exist?(stitch_path)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user_images_controller.rb
class UserImagesController < ApplicationController
  before_action :set_user_image, only: [:show, :edit, :update, :destroy, :stitchify]

  # GET /user_images
  # GET /user_images.json
  def index
    @title = "Welcome to Stitchify!"
    @user_images = UserImage.all
  end

  # GET /user_images/1
  # GET /user_images/1.json
  def show
    @title = "Stitch"
  end

  # GET /user_images/new
  def new
    @title = "Stitch Something!"
    @user_image = UserImage.new
  end

  # GET /user_images/1/edit
  def edit
    @title = "Edit Your Stitch"
  end

  # POST /user_images
  # POST /user_images.json
  def create
    @title = "Stitch Something!"
    @user_image = UserImage.new(sanitized_user_image_params)

    respond_to do |format|
      if @user_image.save
        format.html { redirect_to @user_image, notice: 'User image was successfully created.' }
        format.json { render :show, status: :created, location: @user_image }
      else
        format.html { render :new }
        format.json { render json: @user_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_images/1
  # PATCH/PUT /user_images/1.json
  def update
    @title = "Edit your Stitch"
    respond_to do |format|
      if @user_image.update(sanitized_user_image_params)
        format.html { redirect_to @user_image, notice: 'User image was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_image }
      else
        format.html { render :edit }
        format.json { render json: @user_image.errors, status: :unprocessable_entity }
      end
    end
  end

  def stitchify
    @user_image.stitchify
    redirect_to @user_image, notice: "Successfully stitchified!"
  end

  # DELETE /user_images/1
  # DELETE /user_images/1.json
  def destroy
    @title = "Destroy Your Stitch"
    @user_image.destroy
    respond_to do |format|
      format.html { redirect_to user_images_url, notice: 'User image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_image
      @user_image = UserImage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_image_params
      params.require(:user_image).permit(
        :acknowledged_privacy,
        :grid_width,
        :name,
        :number_of_colors,
        :px_size,
        :stitch_pic)
    end

    def sanitized_user_image_params
      params = user_image_params
      params[:acknowledged_privacy] = params[:acknowledged_privacy] == '1' ? true : false
      params 
    end
end

app/controllers/welcome_controller.rb
class WelcomeController   < ApplicationController
  def index
    @title = "Welcome to Stitchify"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_images_helper.rb
module UserImagesHelper
  def svg(path)
    return File.read(path).html_safe if File.exists?(path)
  end
end

app/views/layouts/_header.html.erb
<div class="header">
  <a href="/"><h1>Stitchifier!</h1></a>

  <div class="link-box">
    <%= link_to 'new image upload', new_user_image_path %>
  </div>

  <div class="title-box">
    <h2><%= @title %></h2>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/header' %>

    <%= yield %>
  </body>
</html>

app/views/user_images/_form.html.erb
<div class="form container">

  <%= form_for @user_image, html: {multipart: true} do |f| %>
    <% if @user_image.errors.any? %>
      <div class="row error-box">
        <div class="alert alert-danger" role="alert">
          <h2><%= pluralize(@user_image.errors.count, "error") %> prohibited this image from being saved:</h2>

          <ul>
            <% @user_image.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>

    <div class="row">
      <%= f.label :name, 'File Name (required):', class: "col-6" %>
      <%= f.text_field :name, class: "col-6" %>
    </div>
    <div class="row">
      <%= f.label :stitch_pic, 'File to Stitch (required):', class: "col-6" %>
      <%= f.file_field :stitch_pic, class: "col-6" %>
    </div>
    <div class="row">
      <div class="alert alert-info">
        <h5>Privacy Statement</h5>
        Stitchifier is a small project ellen works on in her free time, and as a disabled queer woman, her resources are extremely limited. As such, while she will never sell your pictures, she has not committed extensive resources into the privacy and security of your images. Please do not upload anything sensitive.
      </div>

      <div class="col-6">
        <%= f.check_box :acknowledged_privacy, class: "privacy-box" %>
      </div>
      <div class="col-6">
        <%= f.label :acknowledged_privacy, 'I acknowledge the privacy statement above' %>
      </div>


    </div>

    <div class="row">
      <span class="col-sm-12 col-md-6">
        <div class="container">
          <div class="row">
            <%= f.label :grid_width, "Width of grid", class: "col-8" %>
          

            <%= f.number_field :grid_width, min: 2, max: 100, class: "col-4" %>
          </div>
        </div>
      </span>

      <span class="col-sm-12 col-md-6">
        <div class="container">
          <div class="row">
            <%= f.label :px_size, "Grid px size", class: "col-8" %>
        

            <%= f.number_field :px_size, min: 2, max: 15, class: "col-4" %>
          </div>
        </div>
      </span>

      <span class="col-sm-12 col-md-6">
        <div class="container">
          <div class="row">
            <%= f.label :number_of_colors, "Number of colors", class: "col-8" %>
        

            <%= f.number_field :number_of_colors, min: 2, max: 20, class: "col-4" %>
          </div>
        </div>
      </span>
    </div>

    <div class="row">
      <%= f.submit class: "submit-button" %>
    </div>
  <% end %>
</div>

app/views/user_images/edit.html.erb
<h1>Editing User Image</h1>

<%= render 'form', user_image: @user_image %>

<%= link_to 'Show', @user_image %> |
<%= link_to 'Back', user_images_path %>

app/views/user_images/index.html.erb
<div class="index">
  <p id="notice"><%= notice %></p>

  <table class="container table table-striped table-bordered">
    <thead>
      <tr class="row">
        <th class="col-3">Name</th>
        <th class="col-3">Thumbnail</th>
        <th class="col-3">Stitched?</th>
        <th class="col-3"></th>
      </tr>
    </thead>

    <tbody>
      <% @user_images.each do |user_image| %>
        <tr class="row font-weight-light">
          <td class="col-3"><%= link_to user_image.name, user_image %></td>
          <td class="col-3">
            <% if user_image.stitch_pic.url %>
              <%= image_tag user_image.stitch_pic.thumb.url %>
            <% end %>
          </td>
          <td class="col-3">
            <% if user_image.stitched_file? %>
              <strong>yes!</strong>
            <% else %>
              no
            <% end %>
          </td>
          <td class="col-3"><%= link_to 'Edit', edit_user_image_path(user_image) %>
            /
            <%= link_to 'Destroy', user_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </div>
</div>

app/views/user_images/new.html.erb
<h1>New User Image</h1>

<%= render 'form', user_image: @user_image %>

<%= link_to 'Back', user_images_path %>

app/views/user_images/show.html.erb
<div class="show">
  <p id="notice"><%= notice %></p>

  <div class="container">
    <div class="row">
      <div class="col-6"><h5>Name:</h5></div>
      <div class="col-6"><%= @user_image.name %></div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-6"><h5>Grid Width:</h5></div>
      <div class="col-6"><%= @user_image.grid_width %></div>
    </div>
    <div class="row">
      <div class="col-6"><h5>Size of "pixels":</h5></div>
      <div class="col-6"><%= @user_image.px_size %></div>
    </div>
    <div class="row">
      <div class="col-6"><h5>Number of colors:</h5></div>
      <div class="col-6"><%= @user_image.number_of_colors %></div>
    </div>

    <% if @user_image.stitch_pic.url %>
      <div class="container">
        <div class="row">
          <div class="col-6"><h5>Original image:</h5></div>
          <div class="col-6">
            <%= image_tag @user_image.stitch_pic.thumb.url %>
          </div>
        </div>
      </div>
    <% end %>

    <% if @user_image.stitched_file? %>
      <p>
        <%= link_to "Restitch!", stitchify_path(@user_image.id) %> |
        <%= link_to 'Edit', edit_user_image_path(@user_image) %> |
        <%= link_to 'Back', user_images_path %>
      </p>
      <p>
        <%= svg @user_image.stitch_path %>
      </p>
    <% elsif @user_image.stitch_pic.url %>
      <%= link_to "Stitchify!", stitchify_path(@user_image.id) %>
    <% end %>

  </div>
</div>

app/views/welcome/index.html.erb
it's the welcome page!